apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: apache
  template:
    metadata:
      labels:
        component: apache
    spec:
      containers:
        - name: apache
          image: profemzy/lampstack_apache
          ports:
            - containerPort: 80
